### ISSUE TITLE
Docs: Criar um novo readme

### ISSUE THREAD

**Issue by FLuiz22** [FLuiz22/ufroad-api#14]
# OVERVIEW

- O readme tem a função de descrever um projeto, sua equipe e outras informações como uma apresentação para quem vê de fora, logo faz-se necessário ter esse tipo de apresentação para agregar mais valor ao sistema, além de profissionalidade para quem olha de fora;

# TASKS

- Criar o readme com as seguintes informações:
- [x] Descrição do projeto; @danieleolivs 
- [x] Instruções para instalação; @mateusmf4 
- [x] Tecnologias utilizadas; @mateusmf4 
- [x] Versões do sistema; @maahog 
- [x] Desenvolvedores responsáveis; @maahog 
- [x] Licença; @danieleolivs
