### ISSUE TITLE
Feature: Criar os arquivos e as rotas para Usuário

### ISSUE THREAD

**Issue by FLuiz22** [FLuiz22/ufroad-api#2]
# OVERVIEW

- Como descrito na documentação dos requisitos funcionais do projeto, temos a entidade usuário, então, baseado na descrição da entidade no documento, é necessário criar o schema dela bem como os arquivos de service, controller e routes;

# TASKS

- [x] Criar e desenvolver o arquivo User.js;
- [x] Criar e desenvolver o arquivo UserService.js;
- [x] Criar e desenvolver o arquivo UserController.js;
- [x] Criar e desenvolver o arquivo UserRoutes.js;
- [x] Realizar testes no postman para verificar se está tudo certo;

**Comment by FLuiz22** [comment]
# COMMENTS

- Algumas funções para serem desenvolvidas, mas não limitadas a essas são:
  - Encontrar/retornar um usuário;
  - Criar um usuário;
  - Atualizar um usuário;
  - Deletar um usuário;
