### ISSUE TITLE
Feature: Criar rota de login para o usuário

### ISSUE THREAD

**Issue by FLuiz22** [FLuiz22/ufroad-api#20]
# OVERVIEW

- Agora com a rota de usuário desenvolvida, é importante desenvolver uma rota para possibilitar o login do usuário no sistema;

# TASKS

- [x] Desenvolver o AuthService.js;
- [x] Desenvolver o AuthController.js;
- [x] Desenvolver o AuthRoutes.js;
