### ISSUE TITLE
Refactor: Complementar os módulos da Sprint 1

### ISSUE THREAD

**Issue by FLuiz22** [FLuiz22/ufroad-api#22]
# OVERVIEW

- Agora com os principais módulos finalizados alguns pontos não puderam ser feitos pois dependiam de outros, então para finalizar de fato é preciso completar as partes comentadas do código que dependem de outros módulos;

# TASKS

- [x] Complementar o módulo de User;
- [x] Complementar o módulo de Curriculum;
- [x] Complementar o módulo de Course;
- [x] Complementar o módulo de Class;
