### ISSUE TITLE
Feature: Criar os arquivos e as rotas para Curso

### ISSUE THREAD

**Issue by FLuiz22** [FLuiz22/ufroad-api#3]
# OVERVIEW

- Como descrito na documentação dos requisitos funcionais do projeto, temos a entidade curso, então, baseado na descrição da entidade no documento, é necessário criar o schema dela bem como os arquivos de service, controller e routes;

# TASKS

- [x] Criar e desenvolver o arquivo Course.js; @maahog 
- [x] Criar e desenvolver o arquivo CourseService.js; @maahog 
- [ ] Criar e desenvolver o arquivo CourseController.js; @gabysouzz 
- [x] Criar e desenvolver o arquivo CourseRoutes.js; @gabysouzz 
- [ ] Realizar testes no postman para verificar se está tudo certo;

**Comment by FLuiz22** [comment]
# COMMENTS

- Algumas funções para serem desenvolvidas, mas não limitadas a essas são:
  - Encontrar/retornar um curso;
  - Criar um curso;
  - Retornar todos os cursos;
  - Atualizar um curso;
  - Deletar um curso;
