### ISSUE TITLE
Feature: Criar os arquivos e as rotas para Grade

### ISSUE THREAD

**Issue by FLuiz22** [FLuiz22/ufroad-api#4]
# OVERVIEW

- Como descrito na documentação dos requisitos funcionais do projeto, temos a entidade grade, então, baseado na descrição da entidade no documento, é necessário criar o schema dela bem como os arquivos de service, controller e routes;

# TASKS

- [x] Criar e desenvolver o arquivo Curriculum.js;
- [x] Criar e desenvolver o arquivo CurriculumService.js;
- [x] Criar e desenvolver o arquivo CurriculumController.js;
- [x] Criar e desenvolver o arquivo CurriculumRoutes.js;
- [x] Realizar testes no postman para verificar se está tudo certo;

**Comment by FLuiz22** [comment]
# COMMENTS

- Algumas funções para serem desenvolvidas, mas não limitadas a essas são:
  - Encontrar/retornar uma grade;
  - Criar uma grade;
  - Retornar todas as grades;
  - Atualizar uma grade;
  - Deletar uma grade;

**Comment by FLuiz22** [comment]
# REVIEW

- Faltou a função de criação de uma grade, bem como sua respectiva rota;
