### ISSUE TITLE
Feat: Adicionar o populate nos módulos necessários

### ISSUE THREAD

**Issue by FLuiz22** [FLuiz22/ufroad-api#40]
# OVERVIEW

- Os módulos de usuário, grade e curso possuem atributos que referenciam uns aos outros, como usuário armazenando um curso, curso armazenando disciplinas, etc. Esses atributos são apenas ids desses objetos, ou seja, quando o objeto usuário, por exemplo, é retornado ao front, ao invés de carregar o nome do curso e outras informações, ele carrega apenas o id do curso, então o front não sabe o que fazer com essa informação;

- Existe uma função chamada "populate" que pega esse id e preenche aquele atributo com os dados do objeto ao qual o id pertence, assim, solucionando esse problema;

# TASKS

- [x] Adicionar o .populate ao usuário;
- [x] Adicionar o .populate ao curso;
- [x] Adicionar o .populate à grade;

**Comment by danieleolivs** [comment]
https://github.com/FLuiz22/ufroad-api/pull/44
