### ISSUE TITLE
Feature: Criar os arquivos e as rotas para Disciplina

### ISSUE THREAD

**Issue by FLuiz22** [FLuiz22/ufroad-api#5]
# OVERVIEW

- Como descrito na documentação dos requisitos funcionais do projeto, temos a entidade disciplina, então, baseado na descrição da entidade no documento, é necessário criar o schema dela bem como os arquivos de service, controller e routes;

# TASKS

- [x] Criar e desenvolver o arquivo SClass.js;
- [x] Criar e desenvolver o arquivo SClassService.js;
- [x] Criar e desenvolver o arquivo SClassController.js;
- [x] Criar e desenvolver o arquivo SClassRoutes.js;
- [x] Realizar testes no postman para verificar se está tudo certo;

**Comment by FLuiz22** [comment]
# COMMENTS

- Algumas funções para serem desenvolvidas, mas não limitadas a essas são:
  - Retornar todas as disciplinas;
  - Criar uma disciplina;
  - Atualizar uma disciplina;
  - Deletar uma disciplina;
